# persistent-volume.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rag-storage
  namespace: rag-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
