# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
  namespace: rag-app
type: Opaque
data:
  COHERE_API_KEY: <base64-encoded-cohere-api-key>
  DATABASE_URL: <base64-encoded-database-url>
